spring.application.name=yugioh-tracker
spring.datasource.url=jdbc:postgresql://localhost:5433/yugioh_tracker
spring.datasource.username=dovark
spring.datasource.password=devpassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false